name: Run ansible

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  run-ansible:
    runs-on: self-hosted  # Use the runner with label

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 4: Run the Ansible Playbook
      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'  # Avoid host key checking for testing
        run: |
          ansible-playbook -i inventory.yml ANSIBLE_LOG_PATH=./logfile.log playbook.yml

     # Step 5: Post results (Optional)
      - name: print Logs
        run: cat ./logfile.log

